# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4a3161d7a83dbcacb343a94194533a0d244961ccd8022889e8b0fc6eb04f85291e9fbd055a730d01cbe5dc94465b47e4c39153994adb5fe99e6432f305a578

test:
  secret_key_base: a17461db262138e204f20fdbc9171a48d07ff3defbd2cfcbddb35f1b811c8e2738a5eb6ca963c27bbf53b8ff0a29ebf5f69e23fc114a3ff2e21b550883589645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
